#!/bin/bash

source config

cleanup() {
	rm -rf "$HOSTPATH"/{"$DLDIR"{/gz,/ext},"$RESULTDIR"}/
	mkdir -p "$HOSTPATH"/{"$DLDIR"{/gz,/ext},"$RESULTDIR"}/
	chmod 777 "$HOSTPATH"/"$RESULTDIR"/
}

genpkgs() {
	./href > "$HOSTPATH"/"$DLDIR"/urls
	aria2c -d "$HOSTPATH"/"$DLDIR"/gz -c -i "$HOSTPATH"/"$DLDIR"/urls
	rm "$HOSTPATH"/"$DLDIR"/urls
}

extractpkgs() {
	# bsdtar is far better with some of the oddball compression tools the maintainers have used.
	# Blacklisting can just be a grep between 'done' and 'parallel' in the pipeline, e.g. for zipbombs.
	for i in ./"$DLDIR"/gz/*.tar.gz
	do
		printf "%s\n" "$i"
	done | SHELL=/usr/bin/bash parallel -j8 -k '
	TMP={}           # DLDIR/gz/A.tar.gz
	TMP=${TMP##*/}   # A.tar.gz
	TMP=${TMP%.tar.gz} # A
	mkdir ./"'"$DLDIR"'"/ext/"$TMP"
	OUT=$(bsdtar -C ./"'"$DLDIR"'"/ext/"$TMP" -xvf "{}" 2>&1 >/dev/null | grep -v "^x [^:]*$")
	[[ "$OUT" != "" ]] && printf "E: Errors in decompressing %s:\n%b\n\n" "$TMP" "$OUT"
	' > ./"$RESULTDIR"/extractbugs

	pushd ./"$DLDIR"/ext >/dev/null
	chmod 755 --preserve-root ./*/*

	find . -type f -executable | SHELL=/usr/bin/bash parallel -m 'stat -c "%A %n" {}' > "$HOSTPATH"/"$RESULTDIR"/executablebugs 
	find . -type f ! -perm 644 | SHELL=/usr/bin/bash parallel -m 'chmod 644 -c --preserve-root {}'
	popd >/dev/null
}

#cleanup
#genpkgs
#extractpkgs