#!/bin/bash

# If this runs on my real system, bad things will happen.
[[ $(hostname) = "aur-sandbox" ]] || exit 1

source config

update() {
	sudo /usr/bin/pacman -Syu
	sudo systemd-nspawn -D "$NSPAWN_CONTAINER" /usr/bin/pacman -Syu
}

sync() {
	rsync -am --include='*/PKGBUILD' --include='*/' --exclude='*' "$VMHOSTPATH"/"$DLDIR"/ext "$VMWORKDIR"
}

sourceall() {
	rm -rf "$VMTMPDIR"
	mkdir -p "$VMTMPDIR/sourced"
	mkdir -p "$VMTMPDIR/temporary"

	# Blacklist just consists of a grep -v before piping into the parallel operation.
	# Depth 1 is where all the tarbombs went, and all those PKGBUILDS overwrote each other anyway, so it's a scattering of files from many src archives.
	# systemd-nspawn <=207 will need to have msg, msg2, error, warning and plain touched in /usr/bin.  89acb09394 fixed that.
	# TODO: systemd-nspawn is noisy, saying every time a container is created and exits (which gets buffered into parallel)
	find "$VMWORKDIR"/ext -mindepth 2 -type f -name PKGBUILD | grep -v "/openttd-bin-r25151/" | SHELL=/usr/bin/bash parallel -m -j8 "
		sudo systemd-nspawn --machine='container-{#}' --bind-ro=/usr/bin/echo:/usr/bin/msg --bind-ro=/usr/bin/echo:/usr/bin/msg2 --bind-ro=/usr/bin/echo:/usr/bin/error --bind-ro=/usr/bin/echo:/usr/bin/warning --bind-ro=/usr/bin/echo:/usr/bin/plain --bind-ro='$VMHOSTPATH/2.1-nspawn' --bind-ro='$VMHOSTPATH/config' --bind-ro='$VMWORKDIR' --bind='$VMTMPDIR' --private-network -D '$NSPAWN_CONTAINER' /usr/bin/su - $VMUSER -c "'"'"cd $VMHOSTPATH; $VMHOSTPATH/2.1-nspawn '{}'"'"'"
	"
}

archiveresults() {
	# Clean up multiple URLs.  Only include URLs containing ://, after stripping the renaming (so a::url and b::url don't force url to be checked twice) and strip trailing slash.
	cd "$VMTMPDIR"
	cat sources-container-* | sed 's/::/\n/;s/^.*\n//' | cat - urls-container-* | sed '\|://|!d;s|/$||' | awk 'BEGIN{RS=ORS="\n"}!a[$0]++' > urllist
	rm urls-container-* sources-container-*
	tar -zcf "$VMHOSTPATH"/"$RESULTDIR"/sourceall.tar.gz *
}

# update
# sync
sourceall
archiveresults