#!/bin/bash

source config

prep() {
	if [[ ! -d ./res/sourced ]]; then
		bsdtar -C ./res -xzf ./res/sourceall.tar.gz
	fi
}

coalesce() {
	if [[ -f res/goodurls ]]; then
		comm -23 <(sort res/urllist) <(sort res/goodurls) | sponge res/urllist
		rm res/goodurls
	fi
}

urlcheck() {
	SHELL=/usr/bin/bash parallel -N 50 -j50 './3.3-urlcheck "{}"' :::: ./res/urllist >res/goodurls 2>res/faillog
}

genreport() {
	cat <<REPORTHEADER
Each package was sourced in a container with only base and base-devel, with a read-only working directory and no network connection.  This is intentional, since the act of sourcing should not be writing files, downloading files, or using anything that cannot be checked against the dependency array by makepkg first.
This may mean that some instances of a message such as 'wrote to stdout' or 'wrote to stderr' are not where the PKGBUILD actively uses a msg-like function, but where it attempts to download or write a file to disk.

REPORTHEADER

	echo "==========================================================[Extraction]"
	cat res/extractbugs

	if [[ "$VERBOSITY" -ge 3 ]]; then
		echo
		echo "========================================[Executable files in archive]"
		if [[ "$VERBOSITY" -ge 5 ]]; then
			cat res/executablebugs
		else
			sed 's|[^ ]* ./||;s|/|\n|; s|\n.*||' "./res/executablebugs" | sort | uniq
		fi
	fi

	echo
	echo "================================[PKGBUILDs too many directories deep]"
	pushd ./"$DLDIR"/"$EXTDIR"/ >/dev/null
	find . -mindepth 4 -type f -name PKGBUILD
	popd >/dev/null

	echo
	echo "====================================[PKGBUILDs unable to be analysed]"
	pushd ./res/temporary >/dev/null

	if [[ "$VERBOSITY" -ge 3 ]]; then
		for j in $(
			for i in *
			do
				[[ -e "$i" ]] || continue
				echo "${i%%-*}"
			done | uniq)
		do
			echo "${j%%---*}:"
			for k in "$j-"*
			do
				[[ -e "$k" ]] || continue
				TMP="${k%-*}"
				echo "===== ${k##*-} (${TMP##*-}) ====="
				cat "$k"
			done
			echo
		done
	else
		for i in *
		do
			[[ -e "$i" ]] || continue
			echo "${i%%---*}"
		done | uniq 
	fi
	popd >/dev/null

	echo
	echo "=================================================[Main package faults]"
	expac -Sg '%n' base-devel | SHELL=/usr/bin/bash parallel -j8 'pactree -sl {}' | awk '{print $1;}' | awk 'BEGIN{RS=ORS="\n"}!a[$0]++' | SHELL=/usr/bin/bash parallel -j8 'expac -S1 "%n=%v  %P" {} | sed "s/  /\n/g" | grep -v "\.so=\|\.so$\|^$"' | awk 'BEGIN{RS=ORS="\n"}!a[$0]++' > ./"$RESULTDIR"/tmp_basedevel
	expac -S "%n=%v  %P" | sed 's/  /\n/g' > ./"$RESULTDIR"/tmp_allpkgnames
	# Regular expressions below with a character count have to be written {number\} otherwise parallel understands it as the {n} option.  \{\} is interpreted as \{} instead.
	find ./"$RESULTDIR"/sourced -type f | sort | SHELL=/usr/bin/bash parallel -k -N 5 -j8 '
		./3.4-validate '"$VERBOSITY"' "{}"
	'
	rm ./"$RESULTDIR"/{tmp_basedevel,tmp_allpkgnames}
}

VERBOSITY=0
while getopts "v" OPTION; do
	case "$OPTION" in
		v)
			VERBOSITY=$((VERBOSITY+1))
			;;
	esac	
done
[[ "$VERBOSITY" == "0" ]] && VERBOSITY=1

# prep
# coalesce
# urlcheck
# coalesce
# urlcheck
# coalesce
genreport